language: android
jdk:
    - oraclejdk7
    - oraclejdk8
android:
  components:
    - platform-tools
    - tools
    - build-tools-24.0.3
    - android-24
    - extra-android-support
    - extra-android-m2repository

before_install:
    - export JAVA7_HOME=/usr/lib/jvm/java-7-oracle
    - export JAVA8_HOME=/usr/lib/jvm/java-8-oracle
    - export JAVA_HOME=$JAVA8_HOME
script:
    - ./gradlew clean assemble check
after_success:
    - ./gradlew coveralls

# as per http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/
sudo: false
